In [1]:
import numpy as np

In [3]:
list1 = [0,1,2,3,4]
list1

[0, 1, 2, 3, 4]

In [5]:
arr1d = np.array(list1)
arr1d

array([0, 1, 2, 3, 4])

In [6]:
list1.append(5)
list1

[0, 1, 2, 3, 4, 5]

In [7]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [8]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [9]:
list2 = [[1,1,1], [2,2,2], [3,3,3]]
arr2d = np.array(list2)
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [10]:
arr2d.astype("int")

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [11]:
arr2d.astype("str")

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U11')

In [14]:
list1.append("6")
list1

[0, 1, 2, 3, 4, 5, '6']

In [ ]:
np2list = arr2d.tolist()
np2l